from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.wonbot = QtWidgets.QToolButton(self.centralwidget)
        self.wonbot.setGeometry(QtCore.QRect(20, 40, 141, 51))
        self.wonbot.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/wonbot_2_인쇄용-02.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wonbot.setIcon(icon)
        self.wonbot.setIconSize(QtCore.QSize(200, 200))
        self.wonbot.setObjectName("wonbot")
        self.obstracle_icon = QtWidgets.QToolButton(self.centralwidget)
        self.obstracle_icon.setGeometry(QtCore.QRect(660, 50, 41, 41))
        self.obstracle_icon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/obstracle_yes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("icons/obstracle_no.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.obstracle_icon.setIcon(icon1)
        self.obstracle_icon.setIconSize(QtCore.QSize(200, 200))
        self.obstracle_icon.setObjectName("obstracle_icon")
        self.obstracle_alert_status = QtWidgets.QLabel(self.centralwidget)
        self.obstracle_alert_status.setGeometry(QtCore.QRect(530, 50, 121, 31))
        self.obstracle_alert_status.setObjectName("obstracle_alert_status")
        self.human_following_status = QtWidgets.QLabel(self.centralwidget)
        self.human_following_status.setGeometry(QtCore.QRect(180, 50, 171, 31))
        self.human_following_status.setObjectName("human_following_status")
        self.line_following_status = QtWidgets.QLabel(self.centralwidget)
        self.line_following_status.setGeometry(QtCore.QRect(360, 50, 151, 31))
        self.line_following_status.setObjectName("line_following_status")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 120, 121, 41))
        self.pushButton.setObjectName("pushButton")

        self.push_folllow_line = QtWidgets.QPushButton(self.centralwidget)
        self.push_folllow_line.setGeometry(QtCore.QRect(340, 120, 121, 41))
        self.push_folllow_line.setObjectName("push_folllow_line")

        deep_violet = "background-color: #9400D3;"

        self.push_one = QtWidgets.QPushButton(self.centralwidget)
        self.push_one.setGeometry(QtCore.QRect(580, 210, 89, 51))
        self.push_one.setObjectName("push_one")
        self.push_one.setStyleSheet(deep_violet)

        self.push_three = QtWidgets.QPushButton(self.centralwidget)
        self.push_three.setGeometry(QtCore.QRect(580, 270, 89, 51))
        self.push_three.setObjectName("push_three")
        self.push_three.setStyleSheet(deep_violet)

        self.push_two = QtWidgets.QPushButton(self.centralwidget)
        self.push_two.setGeometry(QtCore.QRect(680, 210, 89, 51))
        self.push_two.setObjectName("push_two")
        self.push_two.setStyleSheet(deep_violet)

        self.push_four = QtWidgets.QPushButton(self.centralwidget)
        self.push_four.setGeometry(QtCore.QRect(680, 270, 89, 51))
        self.push_four.setObjectName("push_four")
        self.push_four.setStyleSheet(deep_violet)

        self.go_to_station = QtWidgets.QLabel(self.centralwidget)
        self.go_to_station.setGeometry(QtCore.QRect(630, 170, 101, 31))
        self.go_to_station.setObjectName("go_to_station")
        self.push_go = QtWidgets.QPushButton(self.centralwidget)
        self.push_go.setGeometry(QtCore.QRect(630, 340, 81, 31))
        self.push_go.setCheckable(True)
        self.push_go.setChecked(True)
        self.push_go.setAutoRepeat(False)
        self.push_go.setObjectName("push_go")
        self.start_station = QtWidgets.QLabel(self.centralwidget)
        self.start_station.setGeometry(QtCore.QRect(560, 380, 111, 31))
        self.start_station.setObjectName("start_station")
        self.end_station = QtWidgets.QLabel(self.centralwidget)
        self.end_station.setGeometry(QtCore.QRect(680, 380, 111, 31))
        self.end_station.setObjectName("end_station")
        self.display_img = QtWidgets.QLabel(self.centralwidget)
        self.display_img.setGeometry(QtCore.QRect(140, 210, 341, 201))
        self.display_img.setText("")
        self.display_img.setObjectName("display_img")
        self.battery = QtWidgets.QToolButton(self.centralwidget)
        self.battery.setGeometry(QtCore.QRect(720, 50, 31, 41))
        self.battery.setObjectName("battery")
        self.date_time = QtWidgets.QLabel(self.centralwidget)
        self.date_time.setGeometry(QtCore.QRect(770, 60, 121, 31))
        self.date_time.setText("")
        self.date_time.setObjectName("date_time")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.obstracle_alert_status.setText(_translate("MainWindow", "Obstracle Status"))
        self.human_following_status.setText(_translate("MainWindow", "Human Following Status"))
        self.line_following_status.setText(_translate("MainWindow", "Line Following status"))
        self.pushButton.setText(_translate("MainWindow", "Follow Me"))
        self.push_folllow_line.setText(_translate("MainWindow", "Follow Line"))
        self.push_one.setText(_translate("MainWindow", "One"))
        self.push_three.setText(_translate("MainWindow", "three"))
        self.push_two.setText(_translate("MainWindow", "two"))
        self.push_four.setText(_translate("MainWindow", "four"))
        self.go_to_station.setText(_translate("MainWindow", "Go to Station"))
        self.push_go.setText(_translate("MainWindow", "Go"))
        self.start_station.setText(_translate("MainWindow", "Start Station : 1"))
        self.end_station.setText(_translate("MainWindow", "End Station : 2"))
        self.battery.setText(_translate("MainWindow", "..."))


def main():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    try:
        sys.exit(app.exec_())
    except KeyboardInterrupt:
        # Handle KeyboardInterrupt (Ctrl+C) to exit the application gracefully
        print("Application terminated by user.")
        app.quit()

if __name__ == "__main__":
    main()